apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
  namespace: default
spec:
  metrics:
    - name: error-rate
      count: 3
      interval: 30s
      failureLimit: 2
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{status=~"5.."}[1m])) 
            / 
            sum(rate(http_requests_total[1m])) 
            or vector(0)
      successCondition: result[0] < 0.05
      failureCondition: result[0] >= 0.05
